// examples/svelte-vite-showcase/src/App.svelte
/**
 * @file App.svelte
 *
 * @version 1.0.0
 * @author BleckWolf25
 * @license MIT
 *
 * @summary Source/config file for App.svelte
 *
 * @description
 * Handles module responsibilities for App.svelte.
 *
 * @since 10/06/2026
 * @updated 27/07/2026
 */

// ---------- IMPORTS
<script lang="ts">
  import { useTheme, useForm, createButtonProps, createCardProps, createDialogProps } from '@bleckwolf25/svelte'

  const theme = useTheme({ defaultTheme: 'light' })

  const form = useForm<{ username: string; email: string }>({
    initialValues: { username: '', email: '' },
    validate: (values) => {
      const errors: any = {}
      if (!values.username) errors.username = 'Username is required'
      if (!values.email) errors.email = 'Email is required'
      return errors
    },
  })

  let dialogOpen = false
  const btnProps = createButtonProps({ variant: 'primary', size: 'md' })
  const cardProps = createCardProps({ variant: 'outlined', elevation: 'md' })

  const toggleDialog = () => {
    dialogOpen = !dialogOpen
  }

  const handleFormSubmit = async () => {
    const valid = await form.validate()
    if (valid) {
      alert(`Submitted: ${JSON.stringify($form.values)}`)
    }
  }
</script>

<main style="padding: 2rem; max-width: 800px; margin: 0 auto; font-family: sans-serif;">
  <header style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
    <h1>Evara UI - Svelte 4/5 Showcase</h1>
    <button class="ui-button ui-button--outline" on:click={() => theme.toggleTheme()}>
      Theme: {$theme}
    </button>
  </header>

  <div class={cardProps.class} style="padding: 1.5rem; margin-bottom: 2rem;">
    <h2 style="margin-top: 0;">Interactive Components</h2>
    <div style="display: flex; gap: 1rem; margin-top: 1rem; align-items: center;">
      <button class={btnProps.class} on:click={toggleDialog}>
        Open Svelte Modal
      </button>
      <span class="ui-badge ui-badge--success">Active Svelte Store</span>
    </div>
  </div>

  {#if dialogOpen}
    <div class="ui-dialog__overlay" on:click={toggleDialog}>
      <div class="ui-dialog" style="max-width: 400px;" on:click|stopPropagation>
        <div class="ui-dialog__header">
          <h3 class="ui-dialog__title">Svelte Dialog Modal</h3>
          <button class="ui-dialog__close-button" on:click={toggleDialog}>✕</button>
        </div>
        <div class="ui-dialog__body">
          <p>This modal dialog is powered by @bleckwolf25/svelte and @bleckwolf25/core.</p>
        </div>
        <div class="ui-dialog__footer">
          <button class="ui-button ui-button--secondary" on:click={toggleDialog}>Close</button>
        </div>
      </div>
    </div>
  {/if}

  <div class={cardProps.class} style="padding: 1.5rem;">
    <h2 style="margin-top: 0;">Form Validation Demo</h2>
    <form on:submit|preventDefault={handleFormSubmit}>
      <div style="margin-bottom: 1rem;">
        <label for="username" style="display: block; margin-bottom: 0.5rem; font-weight: 600;">Username</label>
        <input
          id="username"
          type="text"
          class="ui-input"
          value={$form.values.username}
          on:input={(e) => form.setValue('username', e.currentTarget.value)}
        />
        {#if $form.errors.username}
          <span style="color: #ef4444; font-size: 0.875rem;">{$form.errors.username}</span>
        {/if}
      </div>

      <div style="margin-bottom: 1rem;">
        <label for="email" style="display: block; margin-bottom: 0.5rem; font-weight: 600;">Email</label>
        <input
          id="email"
          type="email"
          class="ui-input"
          value={$form.values.email}
          on:input={(e) => form.setValue('email', e.currentTarget.value)}
        />
        {#if $form.errors.email}
          <span style="color: #ef4444; font-size: 0.875rem;">{$form.errors.email}</span>
        {/if}
      </div>

      <button type="submit" class="ui-button ui-button--primary">Submit Form</button>
    </form>
  </div>
</main>

// examples/nuxt-app/app.vue
/**
 * @file app.vue
 *
 * @version 1.0.0
 * @author BleckWolf25
 * @license MIT
 *
 * @summary Source/config file for app.vue
 *
 * @description
 * Handles module responsibilities for app.vue.
 *
 * @since 10/06/2026
 * @updated 27/07/2026
 */

// ---------- IMPORTS
<script setup lang="ts">
// Components and composables like ThemeProvider, Form, FormField, FormItem, FormLabel, FormControl, FormMessage,
// useForm, useTheme, useDisclosure are auto-imported via @evara-ui/nuxt module!

/* eslint-disable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call */
// @ts-expect-error -- Nuxt auto-imports not resolved in standalone tsconfig
const otpValue = ref('')
// @ts-expect-error -- Nuxt auto-imports not resolved in standalone tsconfig
const isModalOpen = ref(false)
// @ts-expect-error -- Nuxt auto-imports not resolved in standalone tsconfig
const disclosure = useDisclosure({ defaultOpen: false })

// @ts-expect-error -- Nuxt auto-imports not resolved in standalone tsconfig
const { form } = useForm({
  initialValues: { email: '' },
  validate: (values: Record<string, string>) => (!values.email ? { email: 'Email required for Nuxt SSR' } : {}),
  onSubmit: (values: Record<string, string>) => { alert(`Nuxt Form Submitted: ${JSON.stringify(values)}`); },
})
/* eslint-enable @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-call */
</script>

<template>
  <ThemeProvider default-theme="light">
    <div style="padding: 3rem; max-width: 800px; margin: 0 auto; font-family: system-ui, sans-serif;">
      <header style="margin-bottom: 2rem;">
        <h1 style="display: flex; align-items: center; gap: 0.75rem;">
          Nuxt 4 + Evara UI
          <Badge color="primary">
            SSR Powered
          </Badge>
        </h1>
        <p style="color: #6b7280;">
          Zero-config component auto-imports & SSR hydration with @evara-ui/nuxt.
        </p>
      </header>

      <Alert
        variant="success"
        show-icon
        style="margin-bottom: 1.5rem;"
      >
        Nuxt module auto-registered all Evara components, composables (useForm, useTheme, useDisclosure), and ThemeProvider!
      </Alert>

      <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(350px, 1fr)); gap: 1.5rem;">
        <!-- Nuxt Form Demo -->
        <Card variant="outline">
          <CardHeader>
            <h3 style="margin: 0;">
              SSR Auto-Imported Form
            </h3>
          </CardHeader>
          <CardBody>
            <Form :form="form">
              <FormField
                v-slot="{ value, onChange, onBlur }"
                name="email"
              >
                <FormItem>
                  <FormLabel>Email Address</FormLabel>
                  <FormControl>
                    <Input
                      type="email"
                      :value="value"
                      placeholder="nuxt@evara.dev"
                      @input="e => onChange(e.target.value)"
                      @blur="onBlur"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              </FormField>
              <Button
                type="submit"
                variant="primary"
                style="margin-top: 1rem;"
              >
                Submit Nuxt Form
              </Button>
            </Form>
          </CardBody>
        </Card>

        <!-- OTP Security Demo -->
        <Card variant="outline">
          <CardHeader>
            <h3 style="margin: 0;">
              2FA Security Module
            </h3>
          </CardHeader>
          <CardBody style="display: flex; flex-direction: column; gap: 1.25rem;">
            <p style="margin: 0; color: #4b5563;">
              Enter 6-digit code:
            </p>
            <InputOTP
              v-model="otpValue"
              :length="6"
            />

            <div style="display: flex; gap: 0.75rem;">
              <Button
                variant="primary"
                @click="isModalOpen = true"
              >
                Verify OTP
              </Button>
              <Button
                variant="secondary"
                @click="disclosure.toggle()"
              >
                Info
              </Button>
            </div>
          </CardBody>
        </Card>
      </div>

      <Dialog v-model:open="isModalOpen">
        <DialogHeader>
          <h3 style="margin: 0;">
            Verification Status
          </h3>
        </DialogHeader>
        <DialogBody>
          <p>Code entered: <strong>{{ otpValue || 'None' }}</strong></p>
        </DialogBody>
        <DialogFooter style="display: flex; justify-content: flex-end;">
          <Button
            variant="primary"
            @click="isModalOpen = false"
          >
            Close
          </Button>
        </DialogFooter>
      </Dialog>
    </div>
  </ThemeProvider>
</template>
