// examples/svelte-vite-showcase/src/App.svelte
/**
 * @file App.svelte
 *
 * @version 1.0.0
 * @author BleckWolf25
 * @license MIT
 *
 * @summary Source/config file for App.svelte
 *
 * @description
 * Handles module responsibilities for App.svelte.
 *
 * @since 10/06/2026
 * @updated 27/07/2026
 */

// ---------- IMPORTS
<script lang="ts">
  import { useTheme, useForm, createButtonProps, createCardProps, createDialogProps } from '@bleckwolf25/svelte'

  const theme = useTheme({ defaultTheme: 'light' })

  const form = useForm<{ username: string; email: string }>({
    initialValues: { username: '', email: '' },
    validate: (values) => {
      const errors: any = {}
      if (!values.username) errors.username = 'Username is required'
      if (!values.email) errors.email = 'Email is required'
      return errors
    },
  })

  let dialogOpen = false
  const btnProps = createButtonProps({ variant: 'primary', size: 'md' })
  const cardProps = createCardProps({ variant: 'outlined', elevation: 'md' })

  const toggleDialog = () => {
    dialogOpen = !dialogOpen
  }

  const handleFormSubmit = async () => {
    const valid = await form.validate()
    if (valid) {
      alert(`Submitted: ${JSON.stringify($form.values)}`)
    }
  }
</script>

<main style="padding: 2rem; max-width: 800px; margin: 0 auto; font-family: sans-serif;">
  <header style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
    <h1>Evara UI - Svelte 4/5 Showcase</h1>
    <button class="ui-button ui-button--outline" on:click={() => theme.toggleTheme()}>
      Theme: {$theme}
    </button>
  </header>

  <div class={cardProps.class} style="padding: 1.5rem; margin-bottom: 2rem;">
    <h2 style="margin-top: 0;">Interactive Components</h2>
    <div style="display: flex; gap: 1rem; margin-top: 1rem; align-items: center;">
      <button class={btnProps.class} on:click={toggleDialog}>
        Open Svelte Modal
      </button>
      <span class="ui-badge ui-badge--success">Active Svelte Store</span>
    </div>
  </div>

  {#if dialogOpen}
    <div class="ui-dialog__overlay" on:click={toggleDialog}>
      <div class="ui-dialog" style="max-width: 400px;" on:click|stopPropagation>
        <div class="ui-dialog__header">
          <h3 class="ui-dialog__title">Svelte Dialog Modal</h3>
          <button class="ui-dialog__close-button" on:click={toggleDialog}>✕</button>
        </div>
        <div class="ui-dialog__body">
          <p>This modal dialog is powered by @bleckwolf25/svelte and @bleckwolf25/core.</p>
        </div>
        <div class="ui-dialog__footer">
          <button class="ui-button ui-button--secondary" on:click={toggleDialog}>Close</button>
        </div>
      </div>
    </div>
  {/if}

  <div class={cardProps.class} style="padding: 1.5rem;">
    <h2 style="margin-top: 0;">Form Validation Demo</h2>
    <form on:submit|preventDefault={handleFormSubmit}>
      <div style="margin-bottom: 1rem;">
        <label for="username" style="display: block; margin-bottom: 0.5rem; font-weight: 600;">Username</label>
        <input
          id="username"
          type="text"
          class="ui-input"
          value={$form.values.username}
          on:input={(e) => form.setValue('username', e.currentTarget.value)}
        />
        {#if $form.errors.username}
          <span style="color: #ef4444; font-size: 0.875rem;">{$form.errors.username}</span>
        {/if}
      </div>

      <div style="margin-bottom: 1rem;">
        <label for="email" style="display: block; margin-bottom: 0.5rem; font-weight: 600;">Email</label>
        <input
          id="email"
          type="email"
          class="ui-input"
          value={$form.values.email}
          on:input={(e) => form.setValue('email', e.currentTarget.value)}
        />
        {#if $form.errors.email}
          <span style="color: #ef4444; font-size: 0.875rem;">{$form.errors.email}</span>
        {/if}
      </div>

      <button type="submit" class="ui-button ui-button--primary">Submit Form</button>
    </form>
  </div>
</main>

// examples/vue-vite-showcase/src/App.vue
/**
 * @file App.vue
 *
 * @version 1.0.0
 * @author BleckWolf25
 * @license MIT
 *
 * @summary Source/config file for App.vue
 *
 * @description
 * Handles module responsibilities for App.vue.
 *
 * @since 10/06/2026
 * @updated 27/07/2026
 */

// ---------- IMPORTS
<script setup lang="ts">
import { ref } from 'vue'
import {
  ThemeProvider,
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormDescription,
  FormMessage,
  useForm,
  Button,
  Card,
  Dialog,
  Slider,
  Badge,
  Alert,
  Pagination,
  Input,
  ProgressBar
} from '@bleckwolf25/vue'

const isDialogOpen = ref(false)
const sliderValue = ref(65)
const currentPage = ref(1)

const { form } = useForm({
  initialValues: { username: '', email: '' },
  validate: (values) => {
    const errors: Record<string, string> = {}
    if (!values.username) errors['username'] = 'Username is required'
    if (!values.email) errors['email'] = 'Email is required'
    return errors
  },
  onSubmit: (values) => {
    alert(`Form Submitted: ${JSON.stringify(values)}`)
  },
})
</script>

<template>
  <ThemeProvider default-theme="light">
    <div style="padding: 2rem; max-width: 900px; margin: 0 auto; font-family: system-ui, sans-serif;">
      <header style="margin-bottom: 2rem; border-bottom: 1px solid var(--ui-color-border, #e5e7eb); padding-bottom: 1rem;">
        <h1 style="display: flex; align-items: center; gap: 0.75rem;">
          Evara UI - Vue 3 Showcase
          <Badge color="success">
            v1.0.0
          </Badge>
        </h1>
        <p style="color: #6b7280;">
          High-performance, accessible Vue 3 design system components built on headless core controllers.
        </p>
      </header>

      <Alert
        variant="info"
        style="margin-bottom: 1.5rem;"
      >
        Welcome to the Vue 3 Vite showcase! All components below are reactive and fully integrated with Evara UI tokens.
      </Alert>

      <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(380px, 1fr)); gap: 1.5rem;">
        <!-- Accessible Form System -->
        <Card variant="outlined">
          <Card.Header>
            <h3 style="margin: 0;">
              Accessible Form System
            </h3>
          </Card.Header>
          <Card.Body>
            <Form :form="form">
              <FormField
                v-slot="{ value, onChange, onBlur }"
                name="username"
              >
                <FormItem>
                  <FormLabel>Username</FormLabel>
                  <FormControl>
                    <Input
                      :value="value"
                      placeholder="Enter username"
                      @input="e => onChange((e.target as HTMLInputElement).value)"
                      @blur="onBlur"
                    />
                  </FormControl>
                  <FormDescription>Your account handler.</FormDescription>
                  <FormMessage />
                </FormItem>
              </FormField>

              <FormField
                v-slot="{ value, onChange, onBlur }"
                name="email"
              >
                <FormItem style="margin-top: 1rem;">
                  <FormLabel>Email Address</FormLabel>
                  <FormControl>
                    <Input
                      type="email"
                      :value="value"
                      placeholder="john@example.com"
                      @input="e => onChange((e.target as HTMLInputElement).value)"
                      @blur="onBlur"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              </FormField>

              <Button
                type="submit"
                variant="primary"
                style="margin-top: 1rem;"
              >
                Submit Form
              </Button>
            </Form>
          </Card.Body>
        </Card>

        <!-- Interactive Controls & Primitives -->
        <Card variant="outlined">
          <Card.Header>
            <h3 style="margin: 0;">
              Radix Compound Dialog & Controls
            </h3>
          </Card.Header>
          <Card.Body style="display: flex; flex-direction: column; gap: 1rem;">
            <div style="display: flex; gap: 0.5rem; flex-wrap: wrap;">
              <Button
                variant="primary"
                @click="isDialogOpen = true"
              >
                Open Dialog
              </Button>
              <Button variant="secondary">
                Secondary
              </Button>
              <Button variant="ghost">
                Ghost
              </Button>
            </div>
            <div>
              <label style="font-weight: 600; display: block; margin-bottom: 0.5rem;">Volume Level ({{ sliderValue }}%)</label>
              <Slider
                v-model="sliderValue"
                :min="0"
                :max="100"
              />
            </div>
            <div>
              <ProgressBar
                :value="sliderValue"
                color="success"
              />
            </div>
          </Card.Body>
        </Card>
      </div>

      <div style="margin-top: 2rem; display: flex; justify-content: center;">
        <Pagination
          v-model:current-page="currentPage"
          :total-pages="5"
        />
      </div>

      <!-- Radix-Style Compound Dialog -->
      <Dialog.Root v-model:open="isDialogOpen">
        <Dialog.Overlay />
        <Dialog.Content>
          <Dialog.Header>
            <Dialog.Title>Evara UI Compound Dialog</Dialog.Title>
            <Dialog.Description>Stateful data-state animation enabled in Vue.</Dialog.Description>
            <Dialog.Close />
          </Dialog.Header>
          <Dialog.Body>
            <p>This is a compound primitive dialog matching Radix UI standards.</p>
          </Dialog.Body>
          <Dialog.Footer>
            <Button
              variant="secondary"
              @click="isDialogOpen = false"
            >
              Close
            </Button>
          </Dialog.Footer>
        </Dialog.Content>
      </Dialog.Root>
    </div>
  </ThemeProvider>
</template>
